general {
	lock_cmd = swaylock -f -i ~/ftp/Background.jpg --indicator-idle-visible
	before_sleep_cmd = swaylock -f -i ~/ftp/Background.jpg --indicator-idle-visible
}

listener {
    # lock screen after 180 seconds
	timeout = 300
	on-timeout = swaylock -f -i ~/ftp/Background.jpg --indicator-idle-visible
}

listener {
    timeout = 600
	on-timeout = systemctl suspend
}
