general {
	lock_cmd = swaylock -f -i ~/.config/Background.* --indicator-idle-visible
	before_sleep_cmd = swaylock -f -i ~/.config/Background.* --indicator-idle-visible
}

listener {
	timeout = 300
	on-timeout = swaylock -f -i ~/.config/Background.* --indicator-idle-visible
}

listener {
    	timeout = 600
	on-timeout = systemctl suspend
}
